#!/bin/bash
#
# Copyright (c) 2017-2018 Gaël PORTAY <gael.portay@savoirfairelinux.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the MIT License.
#

set -e

usage() {
	cat <<EOF
Usage: ${0##*/} [OPTIONS] [TARGET...]

Runs on top of make using dosh as default shell.

For a more thorough description of make, please refers to its help.

Options:
      -F or --dockerfile FILE   Path to the Dockerfile to use.
      -C or --directory DIR     Change to directory before doing anything else.
            --sh                Set /bin/sh as default shell.
      -h or --help              Print usage.
EOF
}

parse_arguments() {
	makeopts=()
	doshopts="--verbose"
	while [ "$#" -ne 0 ]; do
		if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
			usage
			exit 0
		elif [ "$1" = "--sh" ]; then
			doshopts+=" --shell /bin/sh"
			shell_doshopts+=" --shell /bin/sh"
		elif [ "$1" = "DOSHELL=/bin/sh" ]; then
			eval "$1"
		elif [ "$1" = "-F" ] || [ "$1" = "--dockerfile" ]; then
			doshopts+=" $1 $2"
			shift
		elif [ "$1" = "-C" ] || [ "$1" = "--directory" ]; then
			doshopts+=" $1 $2"
			makeopts[${#makeopts[*]}]="$1"
			makeopts[${#makeopts[*]}]="$2"
			shift
		else
			makeopts[${#makeopts[*]}]="$1"
		fi
		shift
	done
}

# Intercept -C option, and strip -F option
parse_arguments "$@"

# Create a container and remove it on exit
# shellcheck disable=SC2086
container="$(dosh $doshopts --detach)"
trap 'docker rm -f $container' 0

# Run make and set docker shell as default shell
set -- "${makeopts[@]}"
exec make SHELL="dosh $shell_doshopts --exec $container" "$@"
